config/routes.rb
Rails.application.routes.draw do
  get 'siteworkers/index'
  get 'siteworkers/new'
  get 'site/index'
  resources :home
  resources :site
  resources :siteworker
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id                   :integer          not null, primary key
#  site_number          :integer
#  facility_name        :string
#  site_address         :string
#  site_city            :string
#  site_state_or_county :string
#  site_postal_code     :string
#  site_country         :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Site < ApplicationRecord
    
end

app/models/siteworker.rb
# == Schema Information
#
# Table name: siteworkers
#
#  id                 :integer          not null, primary key
#  person_first_name  :string
#  person_middle_name :string
#  person_last_name   :string
#  person_role        :text
#  person_number      :string
#  person_email       :string
#  person_telephone   :string
#  person_site_number :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Siteworker < ApplicationRecord
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_home, only: %i[ show edit update destroy ]
  require 'csv'
  # GET /homes or /homes.json
  def index
    @sites = Site.all
    @siteworkers = Siteworker.all
    @sites.load
    @siteworkers.load
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    
    filename2= File.join Rails.root, "source.csv"
        CSV.foreach(filename2, headers: true, :encoding => "ISO-8859-1") do |row|
            person = Siteworker.where(person_number: row["Person Number"]).first_or_create
            person.person_number = row["Person Number"]
            person.person_first_name = row["Person First Name"]
            person.person_middle_name = row["Person Middle Name"]
            person.person_last_name = row["Person Surname"]
            person.person_role = row["Person Role"]
            person.person_telephone = row["Person Telephone"]
            person.person_email = row["Person Email"]
            person.person_site_number = row["Site Number"]
            person.save
            p person.id, row["Person Number"].to_i
        end
        
        filename= File.join Rails.root, "source.csv"
        CSV.foreach(filename, headers: true, :encoding => "ISO-8859-1") do |row|
            site = Site.where(site_number: row["Site Number"]).first_or_create
            site.facility_name = row["Facility Name"]
            site.site_address = row["Site Address"]
            site.site_city = row["Site City"]
            site.site_state_or_county = row["Site State/County"]
            site.site_postal_code = row["Site Zip"]
            site.site_country = row["Country"]
            site.save
            
        end
        redirect_to root_path 
        # head :ok, content_type: "text/html"
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @sites = Site.all
  end
end

app/controllers/siteworker_controller.rb
class SiteworkerController < ApplicationController
  def index
    @siteworkers = Siteworker.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/siteworkers_helper.rb
module SiteworkersHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<div class="min-h-screen bg-white transition duration-500 ease-in-out ">
  <div class="py-10">
    <header>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">
          Site People
        </h1>
      </div>
    </header>
    <main>
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <!-- Replace with your content -->
        <div class="px-4 py-8 sm:px-0">
          <div class="border-4 border-dashed border-gray-200 rounded-lg h-96">
            <p class="text-xl mt-4">Import the Source.csv file (located in your code directory.):</p>
            <%= link_to "Import Source.csv", new_home_path, class:"mt-4 text-white inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
            <% if @sites.count > 0 %>
              <div class="mt-4">
                <p> There are now <%= @sites.count %> Sites.</p>
                <p> There are now <%= @siteworkers.count %> People.</p>
              <% end %>
            </div>
          </div>
          <!-- /End replace -->
        </div>
      </main>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sitepeople</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body>
    <nav class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex">
            <div class="flex-shrink-0 flex items-center">
              <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
              <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-800-text.svg" alt="Workflow">
            </div>
            <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
              <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
              <a href="/home" class="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" >
                Dashboard
              </a>
              <a href="/site" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                Sites
              </a>
              <a href="/siteworker" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                People
              </a>
            </div>
          </div>
          <div class="hidden sm:ml-6 sm:flex sm:items-center">
            <button type="button" class="bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              <span class="sr-only">View notifications</span>
              <!-- Heroicon name: outline/bell -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
            </button>
            <!-- Profile dropdown -->
            <div class="ml-3 relative">
              <div>
                <button type="button" class="max-w-xs bg-white flex items-center text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                  <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="sm:hidden" id="mobile-menu">
        <div class="pt-2 pb-3 space-y-1">
          <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
          <a href="/home" class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
            Dashboard
          </a>
          <a href="/sites" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium" >
            Sites
          </a>
          <a href="/siteworkers" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
            People
          </a>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/site/index.html.erb
<h1 class="mt-4 text-xl">GET /sites</h1>
<% if @sites.count > 0 %>
  <div class="w-full ml-4">
    <% @sites.each do |site| %>
      <ul>
        <li class="mt-4 text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          number: <%= site.site_number %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          facility_name: <%= site.facility_name %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          country: <%= site.site_country %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          address: <%= site.site_address %>
        </li>
      </ui>
    <% end %>
  <% else %>
    <p class="ml-4"> No Sites found</p>
  <% end %>
</div>

app/views/siteworker/index.html.erb
<h1 class="mt-4 text-xl">GET /persons</h1>
<% if @siteworkers.count > 0 %>
  <div class="w-full ml-4">
    <% @siteworkers.each do |siteworker| %>
      <ul>
        <li class="mt-4 text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          external_identifier: <%= siteworker.person_number %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          email: <%= siteworker.person_email %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          first_name: <%= siteworker.person_first_name %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          last_name: <%= siteworker.person_last_name %>
        </li>
        <li class="text-sm font-medium leading-5 text-gray-900 whitespace-no-wrap ">
          roles: <%= siteworker.person_role %>
        </li>
      </ui>
    <% end %>
  <% else %>
    <p class="ml-4"> No People found</p>
  <% end %>
</div>

app/views/siteworker/new.html.erb
<h1>Siteworkers#new</h1>
<p>Find me in app/views/siteworkers/new.html.erb</p>